author = "Marek Maksimczyk"
description = "Marek Maksimczyk's Personal blog about everything" # Site description. Used in meta description
since = "2025 "
opengraph = true # Enable OpenGraph if true
schema = true # Enable Schema
twitter_cards = false # Enable Twitter Cards if true
readmore = true # Show "Read more" button in list if true
authorbox = false # Show authorbox at bottom of pages if true
toc = true # Enable Table of Contents
pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
post_meta = ["author", "date", "categories", "translations" ] # Order of post meta information
mainSections = ["blog"] #
dateformat = "2006-01-02" # Change the format of dates
mathjax = true # Enable MathJax
mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
languageMenuName = "🌐"

[thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[social]
  cached = false # activate cache if true
  # Enable parts of social widget
  linkedin = "marek-maksimczyk-532a4358"
  github = "mandos"
