
name: Build and publish website
run-name: Build and publish website
on: 
    push:
        paths:
          - 'hugo/**' 
          - 'content/**'
jobs:
    Build:
        runs-on: ubuntu-latest
        container:
            image: "docker.io/hugomods/hugo:ci-0.152.2"
        steps:
        - name: Checkout
          uses: actions/checkout@v5  
        - name: Generating page...
          run: |
               ls -al hugo
               hugo mod vendor --source ./hugo
               hugo build --cleanDestinationDir --source ./hugo --ignoreCache
               ls -al hugo/public 
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: website
            path: ./hugo/public
            if-no-files-found: error
                
    Publish:
        needs: Build
        runs-on: ubuntu-latest
        steps:
        - name: Dowload artifact
          uses: actions/download-artifact@v5
          with:
            name: website
            path: public
        - name: Deploy website
          run: ./scripts/deploy.sh ./public
